export const ADMIN_GET_DATA_REQUEST = "ADMIN_GET_DATA_REQUEST";
export const ADMIN_GET_DATA_SUCCESS = "ADMIN_GET_DATA_SUCCESS";
export const ADMIN_GET_DATA_FAILURE = "ADMIN_GET_DATA_FAILURE";
export const ADMIN_POST_PRODUCT_SUCCESS = "ADMIN_POST_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_POST_PRODUCT_SUCCESS";
export const ADMIN_GET_SINGLE_DATA_SUCCESS = "ADMIN_GET_SINGLE_DATA_SUCCESS";
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";
