export const ADMIN_GET_ORDER_REQUEST = "ADMIN_GET_ORDER_REQUEST";
export const ADMIN_GET_ORDER_SUCCESS = "ADMIN_GET_ORDER_SUCCESS";
export const ADMIN_GET_ORDER_FAILURE = "ADMIN_GET_ORDER_FAILURE";

export const ADMIN_ADD_ORDER_REQUEST = "ADMIN_ADD_ORDER_REQUEST";
export const ADMIN_ADD_ORDER_SUCCESS = "ADMIN_ADD_ORDER_SUCCESS";
export const ADMIN_ADD_ORDER_FAILURE = "ADMIN_ADD_ORDER_FAILURE";



